Repository multisolution/multi, pull requests merged in 2019-11, with the labels that each got.

#6 Fix Actions working directory
  .github/workflows/api.yml
Labels: bug

#7 Add Cancel resolver and its tests
  api/app/InMemoryDb.php
  api/composer.lock
  api/docker-compose.yml
  api/index.php
  api/resolvers.php
  api/schema.graphql
  api/src/Database.php
  api/src/DateTimeScalar.php
  api/src/Meeting/Cancel.php
  api/src/Meeting/Create.php
  api/src/Meeting/Meeting.php
  api/src/Meeting/Status/Cancelled.php
  api/src/Meeting/Status/Parser.php
  api/src/Meeting/Status/Scheduled.php
  api/src/Meeting/Status/Status.php
  api/tests/unit/InMemoryDbTest.php
  api/tests/unit/Meeting/CancelTest.php
Labels: enhancement

#14 Add front-end project boot from Next.js
  web/.gitignore
  web/components/button.tsx
  web/next-env.d.ts
  web/package-lock.json
  web/package.json
  web/pages/index.tsx
  web/pages/meeting-rooms.tsx
  web/tsconfig.json
Labels: enhancement

#15 Add Apollo GraphQL setup
  web/lib/apollo.tsx
  web/lib/redirect.ts
  web/package-lock.json
  web/package.json
Labels: enhancement

#16 Editing meetings
  api/resolvers.php
  api/schema.graphql
  api/src/Meeting/Edit.php
  api/tests/unit/Meeting/EditTest.php
Labels: enhancement

#18 ACL
  api/seed.php
  api/src/MeetingRoom/Create.php
  api/src/User/Permission.php
  api/src/User/Permission/CreateMeetingRoom.php
  api/src/User/Permits.php
  api/src/User/Role.php
  api/src/User/Role/Administrator.php
  api/src/User/Role/Collaborator.php
  api/src/User/User.php
  api/tests/unit/MeetingRoom/CreateTest.php
  api/tests/unit/User/PermitsTest.php
Labels: enhancement

#19 Adding Jest and a very simples test example
  web/package-lock.json
  web/package.json
  web/tests/example.test.ts
Labels: enhancement

#20 base layout and styles default
  web/components/global-styled.tsx
  web/components/header.tsx
  web/components/layout.tsx
  web/pages/_app.tsx
  web/pages/_document.tsx
  web/pages/index.tsx
  web/pages/meeting-rooms.tsx
Labels: enhancement

#21 Hot-fit TypeScript
  web/pages/_document.tsx
  web/tests/example.test.ts
Labels: bug

#22 Better name conventions
  .editorconfig
  api/.editorconfig
  web/components/button.tsx
  web/components/global-style.tsx
  web/components/global-styled.tsx
  web/components/header.tsx
  web/components/layout.tsx
  web/lib/apollo.tsx
  web/lib/redirect.ts
  web/package-lock.json
  web/package.json
  web/pages/_app.tsx
  web/pages/_document.tsx
  web/pages/index.tsx
  web/pages/meeting-rooms.tsx
  web/tests/example.test.ts
Labels: enhancement

#23 Creating users!
  api/app/InMemoryMessages.php
  api/composer.lock
  api/index.php
  api/resolvers.php
  api/schema.graphql
  api/src/User/Create.php
  api/src/User/Permission/CreateUser.php
  api/src/User/Role.php
  api/src/User/Role/Administrator.php
  api/src/User/Role/Collaborator.php
Labels: enhancement

#24 Adding types to the web theme
  web/components/global-style.tsx
Labels: enhancement

#27 Working with a real database
  .env.dist
  .gitignore
  README.md
  api/.editorconfig
  api/.env.dist
  api/.gitignore
  api/app/DoctrineDBAL.php
  api/app/InMemoryDb.php
  api/app/dbs.php
  api/docker-compose.yml
  api/index.php
  api/resolvers.php
  api/seed.php
  api/src/Database.php
  api/src/Meeting/Meeting.php
  api/src/Meeting/Room.php
  api/src/MeetingRoom/MeetingRoom.php
  api/src/MeetingRoom/MeetingRooms.php
  api/src/User/Role/Parser.php
  api/src/User/User.php
  db/migrations/V1__Initial_version.sql
  docker-compose.yml
Labels: enhancement

#28 Chore
  .gitignore
  api/.gitignore
  package-lock.json
  web/.gitignore
Labels: enhancement

#32 Fix enum values
  api/app/DoctrineDBAL.php
  api/composer.lock
  api/resolvers.php
  api/src/Meeting/Meeting.php
  api/src/Meeting/Status/Cancelled.php
  api/src/Meeting/Status/EnumType.php
  api/src/Meeting/Status/Parse.php
  api/src/Meeting/Status/Parser.php
  api/src/Meeting/Status/Scheduled.php
  api/src/Meeting/Status/Status.php
  api/src/MeetingRoom/MeetingRooms.php
  api/src/User/AllUsers.php
  api/src/User/Create.php
  api/src/User/Permission/CreateMeetingRoom.php
  api/src/User/Permission/CreateUser.php
  api/src/User/Permission/Permission.php
  api/src/User/Role/Administrator.php
  api/src/User/Role/Collaborator.php
  api/src/User/Role/EnumType.php
  api/src/User/Role/Parse.php
  api/src/User/Role/Parser.php
  api/src/User/Role/Role.php
  api/src/User/User.php
  db/migrations/V1__Initial_version.sql
Labels: bug

#33 Fix Role enum and meeting cancel
  api/app/DoctrineDBAL.php
  api/src/Meeting/Cancel.php
  api/src/User/Create.php
  api/src/User/Permission/Permits.php
  api/src/User/Role/EnumType.php
Labels: bug

#39 Creating meetings
  .env.dist
  api/src/DateTimeScalar.php
  api/src/Meeting/Create.php
  web/components/button.tsx
  web/lib/models.ts
  web/pages/new-meeting.tsx
Labels: enhancement

#40 Fix missing implementations on memory stub
  api/app/InMemoryDb.php
Labels: bug

#43 Calendar query
  api/app/DoctrineDBAL.php
  api/resolvers.php
  api/schema.graphql
  api/src/Database.php
  api/src/Meeting/Calendar.php
Labels: enhancement

#50 Calendar refactoring
  .gitignore
  api/resolvers.php
  api/schema.graphql
  api/src/Meeting/Between.php
  api/src/Meeting/Calendar.php
  api/src/Meeting/Host.php
  api/src/Meeting/Meeting.php
  package-lock.json
Labels: enhancement

#54 sign in style bug resolved
  web/.DS_Store
  web/components/box-header.tsx
  web/components/footer.tsx
  web/components/form.tsx
  web/components/global-style.tsx
  web/components/grid.tsx
  web/components/header.tsx
  web/components/label.tsx
  web/components/layout.tsx
  web/components/room.tsx
  web/components/title-page.tsx
  web/package-lock.json
  web/package.json
  web/pages/create-user.tsx
  web/pages/index-base.tsx
  web/pages/meeting-rooms.tsx
  web/pages/pass-recovery.tsx
  web/pages/signin.tsx
  web/public/assets/img/logo.png
  web/public/assets/img/sala-generica.png
Labels: bug

#56 Restore react-icons
  web/package-lock.json
  web/package.json
Labels: bug

#61 Weekend refactoring!
  .github/workflows/web.yml
  api/src/Meeting/Calendar.php
  web/components/calendar-styles.tsx
  web/components/calendar.tsx
  web/components/form.tsx
  web/components/global-style.tsx
  web/components/grid.tsx
  web/components/loading.tsx
  web/components/new-meeting-form.tsx
  web/components/whoops.tsx
  web/lib/misc.ts
  web/lib/models.ts
  web/pages/meeting-rooms.tsx
  web/pages/pass-recovery.tsx
  web/pages/signin.tsx
Labels: enhancement

#62 Clean ups, checking logging and logging out
  api/resolvers.php
  api/schema.graphql
  web/components/box-header.tsx
  web/components/layout.tsx
  web/components/password-recovery.tsx
  web/lib/check-logged-in.ts
  web/lib/misc.ts
  web/pages/create-user.tsx
  web/pages/index-base.tsx
  web/pages/index.tsx
  web/pages/list-users.tsx
  web/pages/meeting-rooms.tsx
  web/pages/new-meeting.tsx
  web/pages/pass-recovery.tsx
  web/pages/signin.tsx
Labels: enhancement

#74 Titled meetings and restyled form
  api/app/DoctrineDBAL.php
  api/app/InMemoryMessages.php
  api/schema.graphql
  api/src/Meeting/Create.php
  api/src/Meeting/Edit.php
  api/src/Meeting/Meeting.php
  db/migrations/V1__Initial_version.sql
  web/components/button.tsx
  web/components/calendar.tsx
  web/components/form.tsx
  web/components/grid.tsx
  web/components/list-rooms.tsx
  web/components/modal.tsx
  web/components/new-meeting-form.tsx
  web/lib/apollo.tsx
  web/lib/models.ts
  web/pages/meeting-rooms.tsx
  web/pages/signin.tsx
Labels: enhancement

#81 Animating like a pro
  web/components/global-style.tsx
  web/components/modal.tsx
  web/package-lock.json
  web/package.json
Labels: enhancement

#82 Calendar redesign and test fix
  api/app/InMemoryDb.php
  api/app/InMemoryMessages.php
  api/src/Meeting/Calendar.php
  api/tests/unit/Meeting/EditTest.php
  web/components/calendar.tsx
  web/components/form.tsx
  web/components/global-style.tsx
  web/components/list-rooms.tsx
  web/components/modal.tsx
  web/components/new-meeting-form.tsx
  web/components/room-details.tsx
  web/lib/misc.ts
  web/pages/create-user.tsx
  web/pages/meeting-rooms.tsx
  web/tsconfig.json
Labels: bug, enhancement

#88 Strict TS, Doctrine insert and Sentry
  api/app/DoctrineDBAL.php
  api/composer.json
  api/composer.lock
  api/index.php
  api/src/Meeting/Create.php
  web/tsconfig.json
Labels: enhancement

#89 Add ICS generator
  api/composer.json
  api/composer.lock
  api/index.php
  api/src/Http/IcsHandler.php
Labels: enhancement

#90 Sending emails
  api/app/SendGridListener.php
  api/composer.json
  api/composer.lock
  api/index.php
  api/src/Context.php
  api/src/Event/Dispatcher.php
  api/src/Event/Event.php
  api/src/Event/Listener.php
  api/src/Meeting/Create.php
  api/src/Meeting/Created.php
  web/components/layout.tsx
Labels: enhancement

#91 Inviting!
  api/index.php
  api/resolvers.php
  api/schema.graphql
  api/src/User/Create.php
  api/src/User/Invite/Create.php
  api/src/User/Invite/Invitation.php
  api/src/User/Invite/Invite.php
  api/src/User/Permission/CreateInvite.php
  api/src/User/Role/Administrator.php
  web/components/whoops.tsx
  web/lib/models.ts
  web/pages/invite.tsx
  web/pages/pass-recovery.tsx
Labels: enhancement

#96 Dockerfiles for production
  .gitignore
  api/.dockerignore
  api/Dockerfile
  api/index.php
  up.ps1
  web/.dockerignore
  web/Dockerfile
  web/docker-entrypoint.sh
  web/lib/apollo.tsx
  web/next.config.js
  web/pages/signin.tsx
Labels: enhancement
